on:
  push:
    branches:
      - master
    paths:
      - ".github/**"
      - "android/**"
      - "lib/**"
      - "test/**"
      - "pubspec.yaml"
name: SoundOnFire Development
jobs:
  build:
    name: Prepare, Build, Upload
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: "stable" # or: 'dev' or 'beta'

      - name: Prepare & Build
        id: prepare-build
        run: |
          ./.github/scripts/buildAndroid.sh beta
          echo "::set-output name=dir::$(cat tmp_artifact_path.txt)"
          echo "::set-output name=file::$(cat tmp_artifact_name.txt)"

      - name: Upload articfact
        uses: actions/upload-artifact@v1
        with:
          name: ${{ steps.prepare-build.outputs.file }}
          path: ${{ steps.prepare-build.outputs.dir }}
