on:
  push:
    paths:
      - "android/**"
      - "lib/**"
      - "test/**"
name: SoundCloud on Fire
jobs:
  soundcloud-on-fire:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable" # or: 'dev' or 'beta'

      - name: Prepare & Build
        id: prepare-build
        run: |
          flutter pub get
          ./buildAndroid.sh release
          echo "::set-output name=dir::$(cat tmp_artifact_path.txt)"
          echo "::set-output name=file::$(cat tmp_artifact_name.txt)"

      - name: Upload articfact
        uses: actions/upload-artifact@v1
        with:
          name: SoundOnFire
          path: ${{ steps.prepare-build.outputs.dir }}
